# Generated by Django 4.0.6 on 2022-07-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Name', models.CharField(max_length=25, null=True)),
                ('Create_Password', models.CharField(max_length=8, null=True)),
                ('Enter_Email', models.CharField(max_length=50, null=True)),
                ('Enter_Address', models.CharField(max_length=500, null=True)),
                ('Enter_Mobile_Number', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
